platform:
  - x64

environment:
  MSYSTEM: MSYS
  CTEST_OUTPUT_ON_FAILURE: 1

before_build:
  - C:\msys64\usr\bin\pacman --noconfirm --ask 20 --sync --refresh --sysupgrade
  - C:\msys64\usr\bin\pacman --noconfirm --sync --refresh pacman
  - C:\msys64\usr\bin\pacman --noconfirm --sync --refresh git
  - C:\msys64\usr\bin\pacman --noconfirm --needed --sync mingw-w64-x86_64-cmake make mingw-w64-x86_64-toolchain mingw-w64-x86_64-clang

build_script:
  - C:\msys64\usr\bin\bash -lc "$(cygpath ${APPVEYOR_BUILD_FOLDER})/.appveyor.sh"
